MODEL_SPECS = {
    "tiny": {
        "parameters": "39 M",
        "en_only": "tiny.en",
        "multilingual": "tiny",
        "vram": "~1 GB",
        "speed": "~10x",
        "description": "Smallest model. Ideal for quick testing, real-time transcription, or low-resource environments. Fastest option.",
    },
    "base": {
        "parameters": "74 M",
        "en_only": "base.en",
        "multilingual": "base",
        "vram": "~1 GB",
        "speed": "~7x",
        "description": "Lightweight with decent accuracy. A good general-purpose starting point for most users.",
    },
    "small": {
        "parameters": "244 M",
        "en_only": "small.en",
        "multilingual": "small",
        "vram": "~2 GB",
        "speed": "~4x",
        "description": "Balanced speed and accuracy. Recommended default for most use cases.",
    },
    "medium": {
        "parameters": "769 M",
        "en_only": "medium.en",
        "multilingual": "medium",
        "vram": "~5 GB",
        "speed": "~2x",
        "description": "High accuracy. Best when transcription quality matters more than speed.",
    },
    "large": {
        "parameters": "1550 M",
        "en_only": None,
        "multilingual": "large",
        "vram": "~10 GB",
        "speed": "1x",
        "description": "Most accurate model available. Requires significant VRAM. Use for final-quality transcription.",
    },
    "turbo": {
        "parameters": "809 M",
        "en_only": None,
        "multilingual": "turbo",
        "vram": "~6 GB",
        "speed": "~8x",
        "description": "Optimized version of large-v3. Near-large accuracy with much faster speed. Best value for quality and speed.",
    },
}

LANGUAGES = {
    "en": "english",
    "zh": "chinese",
    "de": "german",
    "es": "spanish",
    "ru": "russian",
    "ko": "korean",
    "fr": "french",
    "ja": "japanese",
    "pt": "portuguese",
    "tr": "turkish",
    "pl": "polish",
    "ca": "catalan",
    "nl": "dutch",
    "ar": "arabic",
    "sv": "swedish",
    "it": "italian",
    "id": "indonesian",
    "hi": "hindi",
    "fi": "finnish",
    "vi": "vietnamese",
    "he": "hebrew",
    "uk": "ukrainian",
    "el": "greek",
    "ms": "malay",
    "cs": "czech",
    "ro": "romanian",
    "da": "danish",
    "hu": "hungarian",
    "ta": "tamil",
    "no": "norwegian",
    "th": "thai",
    "ur": "urdu",
    "hr": "croatian",
    "bg": "bulgarian",
    "lt": "lithuanian",
    "la": "latin",
    "mi": "maori",
    "ml": "malayalam",
    "cy": "welsh",
    "sk": "slovak",
    "te": "telugu",
    "fa": "persian",
    "lv": "latvian",
    "bn": "bengali",
    "sr": "serbian",
    "az": "azerbaijani",
    "sl": "slovenian",
    "kn": "kannada",
    "et": "estonian",
    "mk": "macedonian",
    "br": "breton",
    "eu": "basque",
    "is": "icelandic",
    "hy": "armenian",
    "ne": "nepali",
    "mn": "mongolian",
    "bs": "bosnian",
    "kk": "kazakh",
    "sq": "albanian",
    "sw": "swahili",
    "gl": "galician",
    "mr": "marathi",
    "pa": "punjabi",
    "si": "sinhala",
    "km": "khmer",
    "sn": "shona",
    "yo": "yoruba",
    "so": "somali",
    "af": "afrikaans",
    "oc": "occitan",
    "ka": "georgian",
    "be": "belarusian",
    "tg": "tajik",
    "sd": "sindhi",
    "gu": "gujarati",
    "am": "amharic",
    "yi": "yiddish",
    "lo": "lao",
    "uz": "uzbek",
    "fo": "faroese",
    "ht": "haitian creole",
    "ps": "pashto",
    "tk": "turkmen",
    "nn": "nynorsk",
    "mt": "maltese",
    "sa": "sanskrit",
    "lb": "luxembourgish",
    "my": "myanmar",
    "bo": "tibetan",
    "tl": "tagalog",
    "mg": "malagasy",
    "as": "assamese",
    "tt": "tatar",
    "haw": "hawaiian",
    "ln": "lingala",
    "ha": "hausa",
    "ba": "bashkir",
    "jw": "javanese",
    "su": "sundanese",
    "yue": "cantonese",
}

TO_LANGUAGE_CODE = {
    **{language: code for code, language in LANGUAGES.items()},
    "burmese": "my",
    "valencian": "ca",
    "flemish": "nl",
    "haitian": "ht",
    "letzeburgesch": "lb",
    "pushto": "ps",
    "panjabi": "pa",
    "moldavian": "ro",
    "moldovan": "ro",
    "sinhalese": "si",
    "castilian": "es",
    "mandarin": "zh",
}

SORTED_LANGUAGES = sorted(LANGUAGES.items(), key=lambda x: x[1])
